[theme]
# Blue accent color for interactive elements
primaryColor="#4B89DC"
# White background
backgroundColor="#FFFFFF"
# Light gray for widgets
secondaryBackgroundColor="#F0F2F6"
# Dark text for readability
textColor="#262730"
# Font family
font="sans serif"